# Dans ce Notebook, l'input, donc le sbt va etre en sparse encoding, tandis que le bdd sera en one hot encoding

le one hot encoding c'est lorsque les lettres sont remplacées par des matrice de taille = au nombre de caractere.
Ces matrices sont pleines de  sauf a l'indice du caractere codé, ou il y a un 

le sparse, c'est juste que chaque lettre est remplacé directement par un nombre

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data_dir = '/content/drive/MyDrive/DATASET/dataset_ai4utg/Generation test sans pretty print/GenerationTest/'

# Lecture des fichiers 

In [ ]:
list_folder = os.listdir(data_dir)
num_folder = len(list_folder)
number_of_folder = len(list_folder)

# Creation des listes 

In [ ]:
from tqdm import tqdm

In [ ]:
bdd = []
sbt = []

for i  in tqdm (range(1000), desc="loading..."):
  path_iteration = data_dir+'/Dir_Fonction_'+str(i+1)
  bdd_path = path_iteration+"/BDD_Fonction_"+str(i+1)+".txt"
  stb_path = path_iteration+"/SBT_Generation_Output/Fonction_"+str(i+1)+"_SBT.txt"
  bdd_txt = open(bdd_path,'r').read()
  sbt_txt = open(stb_path,'r').read()
  bdd.append(bdd_txt)
  sbt.append(sbt_txt)

loading...: 100%|██████████| 1000/1000 [14:59<00:00,  1.11it/s]


# Creation d'un vocabulaire char by char 

In [ ]:
vocab_bdd = {l for word in bdd for l in word}

In [ ]:
len(vocab_bdd)

49

In [ ]:
vocab_sbt = {l for word in sbt for l in word}

In [ ]:
len(vocab_sbt)

54

# association char to ind

In [ ]:
char_to_ind_bdd = {char : ind for ind,char in enumerate(vocab_bdd)}
ind_to_char_bdd = {ind : char for ind,char in enumerate(vocab_bdd)}

In [ ]:
print(ind_to_char_bdd)

{0: ':', 1: '_', 2: 's', 3: '5', 4: 'C', 5: 't', 6: 'y', 7: 'o', 8: '=', 9: 'f', 10: 'p', 11: '4', 12: 'i', 13: '#', 14: 'r', 15: 'q', 16: 'e', 17: 'n', 18: '3', 19: '0', 20: 'b', 21: ' ', 22: '8', 23: '2', 24: 'w', 25: 'v', 26: 'a', 27: 'u', 28: '1', 29: '\n', 30: 'c', 31: 'd', 32: 'k', 33: 'g', 34: 'h', 35: 'G', 36: 'S', 37: '-', 38: 'F', 39: 'z', 40: 'm', 41: 'l', 42: '6', 43: 'x', 44: '9', 45: 'j', 46: '7', 47: 'W', 48: 'T'}


In [ ]:
print(char_to_ind_bdd)

{':': 0, '_': 1, 's': 2, '5': 3, 'C': 4, 't': 5, 'y': 6, 'o': 7, '=': 8, 'f': 9, 'p': 10, '4': 11, 'i': 12, '#': 13, 'r': 14, 'q': 15, 'e': 16, 'n': 17, '3': 18, '0': 19, 'b': 20, ' ': 21, '8': 22, '2': 23, 'w': 24, 'v': 25, 'a': 26, 'u': 27, '1': 28, '\n': 29, 'c': 30, 'd': 31, 'k': 32, 'g': 33, 'h': 34, 'G': 35, 'S': 36, '-': 37, 'F': 38, 'z': 39, 'm': 40, 'l': 41, '6': 42, 'x': 43, '9': 44, 'j': 45, '7': 46, 'W': 47, 'T': 48}


In [ ]:
char_to_ind_sbt = {char : ind for ind,char in enumerate(vocab_sbt)}
ind_to_char_sbt = {ind : char for ind,char in enumerate(vocab_sbt)}

In [ ]:
print(char_to_ind_sbt)

{'_': 0, 'M': 1, 's': 2, '(': 3, '5': 4, 't': 5, 'y': 6, 'o': 7, 'f': 8, 'I': 9, 'p': 10, 'R': 11, '4': 12, 'i': 13, 'r': 14, 'q': 15, 'e': 16, 'n': 17, 'V': 18, '0': 19, 'b': 20, ' ': 21, '3': 22, '8': 23, '2': 24, 'w': 25, 'v': 26, 'a': 27, 'u': 28, 'E': 29, '1': 30, 'c': 31, 'P': 32, 'd': 33, 'k': 34, 'g': 35, 'h': 36, 'S': 37, 'L': 38, 'B': 39, 'F': 40, ')': 41, 'm': 42, 'z': 43, 'l': 44, '6': 45, 'D': 46, 'x': 47, '9': 48, 'j': 49, '7': 50, 'U': 51, 'N': 52, 'T': 53}


In [ ]:
print(bdd[0])

Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True



In [ ]:
len(sbt[0])

1544

# Conversion en one hot encoding de l'output ( bdd )

# Dimension :  ( nombre fichiers : 1000, nombre max de caractere : 1572, nombre de caracteres differents : 49 bdd)

# Initialisation des matrices de One Hot encoding

In [ ]:
encoded_bdd = np.zeros((number_of_folder,193,49))

# Conversion du sbt et bdd en one hot encoding

In [ ]:
for i,bdd_code in tqdm( enumerate(bdd)):
    for j,char in enumerate (bdd_code):
        encoded_bdd[i,j,char_to_ind_bdd[char]] = 1.

1000it [00:00, 15655.65it/s]


In [ ]:
trainY = encoded_bdd

In [ ]:
trainY.shape

(1000, 193, 49)

# Decodage du one hot encoding

In [ ]:
encoded_sequence_bdd = encoded_bdd[0]

In [ ]:
def decode_bdd ( encoded ):
  decoded_bdd = []
  for i,chars in enumerate(encoded):
    for j,char in enumerate(chars):
        if (char==1):
            decoded_bdd.append(ind_to_char_bdd[j])
  decoded_bdd = ''.join(decoded_sequence_bdd)
  return decoded_bdd

In [ ]:
print(decode_bdd(encoded_sequence_bdd))

Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True



In [ ]:
ind_space_sbt = char_to_ind_sbt[' ']

# Encodage du sbt

# Encodage en char to char but sparse

# dimmension : ( nombre fichiers : 1000, nombre de char max : 1572)

In [ ]:
encoded_sbt_char_sparse = np.full((number_of_folder,1572),ind_space_sbt)

In [ ]:
for i,sbt_code in enumerate(sbt):
    for j,char in enumerate (sbt_code):
        encoded_sbt_char_sparse[i,j] = char_to_ind_sbt[char]

In [ ]:
print(encoded_sbt_char_sparse.shape)

(1000, 1572)


In [ ]:
trainX = encoded_sbt_char_sparse

In [ ]:
trainX.shape

(1000, 1572)

# Decodage en sparse char to char

In [ ]:
def decode_pred_sequence(pred_sequence):
    decoded_sequence = []
    for char in pred_sequence:
        decoded_sequence.append(ind_to_char_bdd[char])
    decoded_sequence = ''.join(decoded_sequence)
    return decoded_sequence

In [ ]:
decoded_sequence_sbt_sparse = []
encoded_sbt = encoded_sbt_char_sparse[0]
for seq in encoded_sbt:
    decoded_sequence_sbt_sparse.append(ind_to_char_sbt[seq])
    
decoded_sequence_sbt_sparse = ''.join(decoded_sequence_sbt_sparse)
print(decoded_sequence_sbt_sparse)

 ( MethodDeclaration ( Modifier public  ) Modifier public  ( Modifier static  ) Modifier static  ( SimpleName Fonction_1 ) SimpleName Fonction_1 ( Parameter ( PrimitiveType int ) PrimitiveType int ( SimpleName b ) SimpleName b ) Parameter ( Parameter ( PrimitiveType int ) PrimitiveType int ( SimpleName c ) SimpleName c ) Parameter ( PrimitiveType boolean ) PrimitiveType boolean ( BlockStmt ( ExpressionStmt ( VariableDeclarationExpr ( VariableDeclarator ( PrimitiveType int ) PrimitiveType int ( SimpleName d ) SimpleName d ( UnaryExpr ( IntegerLiteralExpr 724 ) IntegerLiteralExpr 724 ) UnaryExpr ) VariableDeclarator ) VariableDeclarationExpr ) ExpressionStmt ( ExpressionStmt ( VariableDeclarationExpr ( VariableDeclarator ( PrimitiveType int ) PrimitiveType int ( SimpleName a ) SimpleName a ( IntegerLiteralExpr 507 ) IntegerLiteralExpr 507 ) VariableDeclarator ) VariableDeclarationExpr ) ExpressionStmt ( ExpressionStmt ( VariableDeclarationExpr ( VariableDeclarator ( PrimitiveType boolean

In [ ]:
len(decoded_sequence_sbt_sparse)

1572

# Creation d'un dataset

# X : sbt en sparse

# Y : bdd en one hot encoding

In [ ]:
dataset_sparse = tf.data.Dataset.from_tensor_slices((encoded_sbt_char_sparse,encoded_bdd))

In [ ]:
for input,output in dataset_sparse:
    print('input :',input)
    print('output :',output)

    break

input : tf.Tensor([21  3 21 ... 21 21 21], shape=(1572,), dtype=int64)
output : tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(193, 49), dtype=float64)


# Creation du Modele

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, Dropout, TimeDistributed, LSTM, Bidirectional, Embedding, RepeatVector
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
def create_model(src_vocab, tar_vocab, src_timesteps, tar_timesteps, n_units):
    # Create the model
    model = Sequential()
    model.add(Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True))
    model.add(LSTM(n_units))
    model.add(RepeatVector(tar_timesteps))
    model.add(LSTM(n_units, return_sequences=True))
    model.add(TimeDistributed(Dense(tar_vocab, activation='softmax')))
    return model
 
# Create model
model = create_model(len(vocab_sbt)+1, len(vocab_bdd), 1572, 193, 512)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 1572, 512)         28160     
_________________________________________________________________
lstm_14 (LSTM)               (None, 512)               2099200   
_________________________________________________________________
repeat_vector_7 (RepeatVecto (None, 193, 512)          0         
_________________________________________________________________
lstm_15 (LSTM)               (None, 193, 512)          2099200   
_________________________________________________________________
time_distributed_5 (TimeDist (None, 193, 49)           25137     
Total params: 4,251,697
Trainable params: 4,251,697
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(trainX, trainY,batch_size = 128, epochs=180, validation_split=0.1)

Epoch 1/180
8/8 [==============================] - 27s 3s/step - loss: 3.0593 - accuracy: 0.2124 - val_loss: 3.0782 - val_accuracy: 0.2124
Epoch 2/180
8/8 [==============================] - 27s 3s/step - loss: 3.0584 - accuracy: 0.2124 - val_loss: 3.0682 - val_accuracy: 0.2176
Epoch 3/180
8/8 [==============================] - 27s 3s/step - loss: 3.0423 - accuracy: 0.2163 - val_loss: 3.0486 - val_accuracy: 0.2139
Epoch 4/180
8/8 [==============================] - 27s 3s/step - loss: 3.0163 - accuracy: 0.2149 - val_loss: 3.0116 - val_accuracy: 0.2176
Epoch 5/180
8/8 [==============================] - 27s 3s/step - loss: 2.9797 - accuracy: 0.2119 - val_loss: 2.9703 - val_accuracy: 0.2136
Epoch 6/180
8/8 [==============================] - 27s 3s/step - loss: 2.9465 - accuracy: 0.2155 - val_loss: 2.9371 - val_accuracy: 0.2124
Epoch 7/180
8/8 [==============================] - 27s 3s/step - loss: 2.9158 - accuracy: 0.2256 - val_loss: 2.9002 - val_accuracy: 0.2294
Epoch 8/180
8/8 [==========

In [ ]:
model.save('v1_char_by_char_target_ohe.h5')

In [ ]:
#from tensorflow.keras.models import load_model
#model = load_model('v1_char_by_char_target_ohe (4).h5')

# Test

In [ ]:
for n in range (10):
  test_input = trainX[n]
  test_input = np.expand_dims(test_input,0)
  #print(test_input.shape)
  prediction = model.predict(test_input)[0]
  #print(prediction.shape)
  sequence_prediction = []
  for i, char in enumerate(prediction):
    sequence_prediction.append(np.argmax(char))
    decoded_sequence = []
  for char in sequence_prediction:
    decoded_sequence.append(ind_to_char_bdd[char])
  decoded_sequence = ''.join(decoded_sequence)
  print('Predicted BDD  ',n+1,' :')
  print('\n')
  print(decoded_sequence)
  print('\n')
  print('Expected BDD ',n+1,' :')
  print('\n')
  print(decode_bdd(trainY[n]))

Predicted BDD   1  :


xy7#pqy:budy3Tb#dybx9f3#C9fc5k



bbmbudy3Tb#dybqy6pj###9blqpy
bb-3yf7qC9:bhWWcx9f3#C9fcc5cc5
bbbbwC yfbbbbbbbbb7fWbbbbbb55

bbbbbdyfbbbbjjjjx9f3#C9fcccbbbbbbbddfbbdyyyyypp#bbddppWbbbyyqqpyy





Expected BDD  1  :


Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True

Predicted BDD   2  :


xy7#pqy:budy3Tb#dybx9f3#C9fc5k



bbmbudy3Tb#dybqy6pj###9blqpy
bb-3yf7qC9:bhWWcx9f3#C9fcc5cc5
bbbbwC yfbbbbbbbbb7fWbbbbbb55

bbbbbdyfbbbbjjjjx9f3#C9fcccbbbbbbbddfbbdyyyyypp#bbddppWbbbyyqqpyy





Expected BDD  2  :


Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True

Predicted BDD   3  :


xy7#pqy:budy3Tb#dybx9f3#C9fc5k



bbmbudy3Tb#dybqy6pj###9blqpy
bb-3yf7qC9:bhWWcx9f3#C9fcc5cc5
bbbbwC yfbbbbbbbbb7fWbbbbbb55

bbbb