In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data_dir = '/content/drive/MyDrive/DATASET/dataset_ai4utg/Generation test sans pretty print/GenerationTest/'

# Lecture des fichiers 

In [ ]:
list_folder = os.listdir(data_dir)
num_folder = len(list_folder)
number_of_folder = len(list_folder)

# Creation des listes 

In [ ]:
from tqdm import tqdm

In [ ]:
bdd = []
sbt = []

for i  in tqdm (range(1000), desc="loading..."):
  path_iteration = data_dir+'/Dir_Fonction_'+str(i+1)
  bdd_path = path_iteration+"/BDD_Fonction_"+str(i+1)+".txt"
  stb_path = path_iteration+"/SBT_Generation_Output/Fonction_"+str(i+1)+"_SBT.txt"
  bdd_txt = open(bdd_path,'r').read()
  sbt_txt = open(stb_path,'r').read()
  bdd.append(bdd_txt)
  sbt.append(sbt_txt)

loading...: 100%|██████████| 1000/1000 [28:04<00:00,  1.68s/it]


# Creation d'un vocabulaire char by char 

In [ ]:
print(bdd[:1000])

['Feature: Check the Fonction_1\n\n\n  # Check the result to True\n  Scenario: bdd_Fonction_1_1\n    Given b = -977 and c = 759\n    When i call Fonction_1\n    Then the result should be True\n', 'Feature: Check the Fonction_2\n\n\n  # Check the result to True\n  Scenario: bdd_Fonction_2_1\n    Given k = -363 and m = 399\n    When i call Fonction_2\n    Then the result should be True\n', 'Feature: Check the Fonction_3\n\n\n  # Check the result to True\n  Scenario: bdd_Fonction_3_1\n    Given n = 465 and x = 148\n    When i call Fonction_3\n    Then the result should be True\n', 'Feature: Check the Fonction_4\n\n\n  # Check the result to True\n  Scenario: bdd_Fonction_4_1\n    Given e = -968 and u = -429\n    When i call Fonction_4\n    Then the result should be True\n', 'Feature: Check the Fonction_5\n\n\n  # Check the result to True\n  Scenario: bdd_Fonction_5_1\n    Given h = 389 and a = 1379\n    When i call Fonction_5\n    Then the result should be True\n', 'Feature: Check the Fonc

In [ ]:

vocab_bdd = {l for word in bdd for l in word}
vocab_bdd

In [ ]:
len(vocab_bdd)

49

In [ ]:
vocab_sbt = {l for word in sbt for l in word}
vocab_sbt

{' ',
 '(',
 ')',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'B',
 'D',
 'E',
 'F',
 'I',
 'L',
 'M',
 'N',
 'P',
 'R',
 'S',
 'T',
 'U',
 'V',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [ ]:
len(vocab_sbt)

54

In [ ]:
max_len_sequence_sbt = max([len(x) for x in sbt])
print('len max sbt :',max_len_sequence_sbt)
max_len_sequence_bdd = max([len(x) for x in bdd])
print('len max bdd :',max_len_sequence_bdd)

len max sbt : 1572
len max bdd : 193


# association char to ind

In [ ]:
char_to_ind_bdd = {char : ind for ind,char in enumerate(vocab_bdd)}
ind_to_char_bdd = {ind : char for ind,char in enumerate(vocab_bdd)}


In [ ]:
ind_to_char_bdd


{0: 'w',
 1: 'r',
 2: '0',
 3: 'i',
 4: '=',
 5: 'd',
 6: 't',
 7: 'k',
 8: 'f',
 9: 'F',
 10: 'b',
 11: 'n',
 12: '7',
 13: 'o',
 14: 'l',
 15: 'c',
 16: 'W',
 17: 'm',
 18: 'v',
 19: '4',
 20: 'S',
 21: '3',
 22: ' ',
 23: '#',
 24: 'a',
 25: '\n',
 26: 'u',
 27: 'h',
 28: 'e',
 29: 's',
 30: 'x',
 31: ':',
 32: 'z',
 33: 'T',
 34: '9',
 35: '-',
 36: '6',
 37: 'y',
 38: 'g',
 39: 'j',
 40: 'C',
 41: '2',
 42: 'p',
 43: '1',
 44: '8',
 45: '_',
 46: 'q',
 47: '5',
 48: 'G'}

In [ ]:
char_to_ind_bdd

{'\n': 25,
 ' ': 22,
 '#': 23,
 '-': 35,
 '0': 2,
 '1': 43,
 '2': 41,
 '3': 21,
 '4': 19,
 '5': 47,
 '6': 36,
 '7': 12,
 '8': 44,
 '9': 34,
 ':': 31,
 '=': 4,
 'C': 40,
 'F': 9,
 'G': 48,
 'S': 20,
 'T': 33,
 'W': 16,
 '_': 45,
 'a': 24,
 'b': 10,
 'c': 15,
 'd': 5,
 'e': 28,
 'f': 8,
 'g': 38,
 'h': 27,
 'i': 3,
 'j': 39,
 'k': 7,
 'l': 14,
 'm': 17,
 'n': 11,
 'o': 13,
 'p': 42,
 'q': 46,
 'r': 1,
 's': 29,
 't': 6,
 'u': 26,
 'v': 18,
 'w': 0,
 'x': 30,
 'y': 37,
 'z': 32}

In [ ]:
char_to_ind_sbt = {char : ind for ind,char in enumerate(vocab_sbt)}
ind_to_char_sbt = {ind : char for ind,char in enumerate(vocab_sbt)}

In [ ]:
char_to_ind_sbt['8']

48

In [ ]:
print(bdd[0])

Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True



# Conversion en one hot encoding, dimension ( nombre fichiers : 1000, nombre max de caractere : 1572, nombre de caracteres differents : 49 bdd, 54 sbt )

# Initialisation des matrices de One Hot encoding

In [ ]:
encoded_bdd = np.zeros((number_of_folder,1572,54))
encoded_sbt = np.zeros((number_of_folder,1572,54))

# Conversion du sbt et bdd en one hot encoding

In [ ]:
for i,bdd_code in tqdm( enumerate(bdd)):
    for j,char in enumerate (bdd_code):
        encoded_bdd[i,j,char_to_ind_bdd[char]] = 1.

1000it [00:00, 12199.91it/s]


In [ ]:
for i,sbt_code in tqdm( enumerate(sbt)):
    for j,char in enumerate (sbt_code):
        encoded_sbt[i,j,char_to_ind_sbt[char]] = 1.

1000it [00:00, 1340.25it/s]


In [ ]:
encoded_bdd.shape

(1000, 1572, 54)

In [ ]:
encoded_sbt.shape

(1000, 1572, 54)

# Decodage du one hot encoding

In [ ]:
decoded_sequence_bdd = []
encoded_sequence_bdd = encoded_bdd[0]
for i,chars in enumerate(encoded_sequence_bdd):
    for j,char in enumerate(chars):
        if (char==1):
            decoded_sequence_bdd.append(ind_to_char_bdd[j])
decoded_sequence_bdd = ''.join(decoded_sequence_bdd)

In [ ]:
decoded_sequence_sbt = []
encoded_sequence_sbt = encoded_sbt[0]
for i,chars in enumerate(encoded_sequence_sbt):
    for j,char in enumerate(chars):
        if (char==1):
            decoded_sequence_sbt.append(ind_to_char_sbt[j])
decoded_sequence_sbt = ''.join(decoded_sequence_sbt)

In [ ]:
print(decoded_sequence_bdd)
print(decoded_sequence_sbt)

Feature: Check the Fonction_1


  # Check the result to True
  Scenario: bdd_Fonction_1_1
    Given b = -977 and c = 759
    When i call Fonction_1
    Then the result should be True

 ( MethodDeclaration ( Modifier public  ) Modifier public  ( Modifier static  ) Modifier static  ( SimpleName Fonction_1 ) SimpleName Fonction_1 ( Parameter ( PrimitiveType int ) PrimitiveType int ( SimpleName b ) SimpleName b ) Parameter ( Parameter ( PrimitiveType int ) PrimitiveType int ( SimpleName c ) SimpleName c ) Parameter ( PrimitiveType boolean ) PrimitiveType boolean ( BlockStmt ( ExpressionStmt ( VariableDeclarationExpr ( VariableDeclarator ( PrimitiveType int ) PrimitiveType int ( SimpleName d ) SimpleName d ( UnaryExpr ( IntegerLiteralExpr 724 ) IntegerLiteralExpr 724 ) UnaryExpr ) VariableDeclarator ) VariableDeclarationExpr ) ExpressionStmt ( ExpressionStmt ( VariableDeclarationExpr ( VariableDeclarator ( PrimitiveType int ) PrimitiveType int ( SimpleName a ) SimpleName a ( IntegerLiteralE

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((encoded_sbt,encoded_bdd))

In [ ]:
for input,output in dataset:
    print('input :',input)
    print('output :',output)

    break

input : tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(1572, 54), dtype=float64)
output : tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(1572, 54), dtype=float64)


# Creation du Modele

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, Dropout, TimeDistributed, LSTM, Bidirectional, Embedding, RepeatVector,Input
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
model = Sequential()
#model.add(Input(shape=(1572, 54)))
model.add(Embedding(len(vocab_sbt),256))
#model.add(Embedding(len(vocab_sbt),256,input_length=1572))
#model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(Dense(1024, activation='relu'))
print(model.input_shape)
model.add(Dropout(0.5))
model.add(Dense(54, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

(None, None)


In [ ]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 256)         13824     
_________________________________________________________________
bidirectional (Bidirectional (None, None, 512)         1050624   
_________________________________________________________________
dense (Dense)                (None, None, 1024)        525312    
_________________________________________________________________
dropout (Dropout)            (None, None, 1024)        0         
_________________________________________________________________
dense_1 (Dense)              (None, None, 54)          55350     
Total params: 1,645,110
Trainable params: 1,645,110
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(dataset,batch_size = 128, epochs=10)

Epoch 1/10


ValueError: ignored

# Test

In [ ]:
for i in range(10):
  true_translation = df['bdd'][i]
  #original_text = lines_en[i]
  #print(original_text)
  print(' true bdd : \n',true_translation)

  #new_tmp = np.expand_dims(tmp_x[i],axis=0)
  #print(new_tmp.shape)
  prediction = model.predict(padded_sbt[i])
  prediction = np.squeeze(prediction, axis=1)
  pred_sequence = []
  for i in range(len(prediction)):
      pred_sequence.append(np.argmax(prediction[i]))
  true_pred = sequence_to_sentence(pred_sequence, tokenizer_bdd)
  print('prediction bdd: \n',true_pred)
  print("\n")

