In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf 

In [2]:
path_to_file = 'shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [5]:
print(text[4500:4800])

converted are
  From his low tract and look another way:
    So thou, thy self out-going in thy noon:
    Unlooked on diest unless thou get a son.


                     8
  Music to hear, why hear'st thou music sadly?
  Sweets with sweets war not, joy delights in joy:
  Why lov'st thou that which t


prendre les caracteres uniques a l'interieur du texte -> convertir le texte en un set 


In [6]:
vocab = sorted(set(text))

In [54]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [7]:
len(vocab)

84

creer un nombre pour chaque element de cette liste 

In [ ]:
for pair in enumerate(vocab):
  print(pair)

passer d'un caractere a une lettre

In [9]:
char_to_ind = {char : ind for ind, char in enumerate(vocab)}
#char_to_ind

In [10]:
char_to_ind['H']

33

passer d'un indice au caractere

In [11]:
ind_to_char = np.array(vocab)

In [53]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [12]:
ind_to_char[33]

'H'

pour tout le texte, on veut l'encoder avec des entiers

In [13]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [14]:
encoded_text.shape

(5445609,)

In [15]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [16]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

on va selectionner la taille du batch, sachant que les vers possède une repetitions avec les rimes, il faut que notre modele selectionne au moins 3 lignes 

In [17]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [18]:
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
''' # on selectionne les triples cotes car il y a des retour a la ligne que nous voulons prendre en compte

In [19]:
len(lines )

133

In [20]:
seq_len = 120

calculer le nombre total de sequence contenu dans notre dataset

In [21]:
total_num_seq = len(text)// ( seq_len + 1)#+ 1 car indexe commence a 0

In [22]:
total_num_seq

45005

creation les sequence d 'entrainement, avec les outil dataset de tensorflow 

In [23]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [24]:
type(char_dataset) 

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [25]:
for item in char_dataset.take(500):
  print(ind_to_char[item.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


combine les elements consecutifs de ce dataset en batch

In [26]:
sequence = char_dataset.batch(seq_len+1, drop_remainder=True)

sequence de texte cible : saisir la sequence de texte d'entree, assigner la sequence de texte cible ( sequence d'entrée decalée d'un pas en avant ) les grouper ensemble en 1 tupple

In [27]:
def create_seq_targets(seq):
  input_text = seq[:-1]#derniere caractere non inclu
  target_text = seq[1:]
  return input_text, target_text

applquer ce changement a tout le dataset

In [28]:
dataset = sequence.map(create_seq_targets)

affiche sequence d'entrée sous format code et txt puis affiche la sequence cible 

In [29]:
for input_txt, target_txt in dataset.take(1):
  print(input_txt.numpy())
  print(''.join(ind_to_char[input_txt.numpy()]))
  print('\n')
  print(target_txt.numpy())
  print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [30]:
batch_size = 128

In [31]:
buffer_size = 10000 # on prend 10 000 des elemetns et on melange, sur des gros dataset si on choisit pas de buffer ca peut creer des erreurs

Melanger les lots

In [32]:
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [33]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

creation du modele

In [34]:
vocab_size = len(vocab)

In [35]:
vocab_size

84

In [36]:
embed_dim = 64 # meme ordre de grandeur que le vocab

In [37]:
rnn_neurons = 1026

fonction qui va creer une fonction de perte

In [38]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [39]:
def sparse_cat_losses( y_true, y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, LSTM, Dropout

In [41]:
def create_model(vocab_size, embed_dim,rnn_neurons, batch_size):
  model=Sequential()
  model.add(Embedding(vocab_size, embed_dim, batch_input_shape = [batch_size, None]))
  model.add(GRU(rnn_neurons, return_sequences=True, stateful=True,
                recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile(optimizer='adam', loss=sparse_cat_losses)
  return model

In [42]:
model = create_model(vocab_size = vocab_size, embed_dim=embed_dim, 
                     rnn_neurons=rnn_neurons,
                     batch_size = batch_size
                     )

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [44]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_prediction = model(input_example_batch)

In [45]:
example_batch_prediction.shape

TensorShape([128, 120, 84])

retourne un tableau contenant tout les probabilité pour chaque caracetere 

In [46]:
sampled_indices = tf.random.categorical(example_batch_prediction[0], num_samples=1)

renvoit les indices des caractere qui on ete selectionnés, il faut le donner de cette facon a ind to char

In [47]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[56],
       [33],
       [15],
       [ 0],
       [74],
       [13],
       [22],
       [ 6],
       [24],
       [57],
       [61],
       [19],
       [51],
       [78],
       [53],
       [ 1],
       [12],
       [10],
       [60],
       [ 5],
       [34],
       [ 6],
       [18],
       [17],
       [75],
       [55],
       [20],
       [43],
       [51],
       [70],
       [45],
       [ 0],
       [ 3],
       [52],
       [62],
       [67],
       [65],
       [71],
       [25],
       [27],
       [29],
       [72],
       [81],
       [66],
       [ 8],
       [45],
       [13],
       [28],
       [39],
       [17],
       [48],
       [47],
       [ 0],
       [47],
       [69],
       [68],
       [53],
       [80],
       [72],
       [24],
       [46],
       [68],
       [75],
       [40],
       [12],
       [74],
       [33],
       [70],
       [45],
       [40],
       [53],
       [70],
       [54],
   

transforme en format souhaité

In [48]:
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

In [49]:
sampled_indices

array([56, 33, 15,  0, 74, 13, 22,  6, 24, 57, 61, 19, 51, 78, 53,  1, 12,
       10, 60,  5, 34,  6, 18, 17, 75, 55, 20, 43, 51, 70, 45,  0,  3, 52,
       62, 67, 65, 71, 25, 27, 29, 72, 81, 66,  8, 45, 13, 28, 39, 17, 48,
       47,  0, 47, 69, 68, 53, 80, 72, 24, 46, 68, 75, 40, 12, 74, 33, 70,
       45, 40, 53, 70, 54,  2,  9, 15, 57, 67, 34, 18, 67, 53, 41, 50, 39,
       82, 72, 64, 35, 83, 27,  4, 48, 23, 29, 56, 23, 48, 53, 34,  6, 24,
        5, 67, 12,  5, 70, 32, 38, 54, 79, 75, 17, 20, 18, 23, 75, 70, 64,
        7])

In [50]:
ind_to_char[sampled_indices]

array(['a', 'H', '4', '\n', 's', '2', ';', '(', '>', 'b', 'f', '8', 'Z',
       'w', ']', ' ', '1', '.', 'e', "'", 'I', '(', '7', '6', 't', '`',
       '9', 'R', 'Z', 'o', 'T', '\n', '"', '[', 'g', 'l', 'j', 'p', '?',
       'B', 'D', 'q', 'z', 'k', ',', 'T', '2', 'C', 'N', '6', 'W', 'V',
       '\n', 'V', 'n', 'm', ']', 'y', 'q', '>', 'U', 'm', 't', 'O', '1',
       's', 'H', 'o', 'T', 'O', ']', 'o', '_', '!', '-', '4', 'b', 'l',
       'I', '7', 'l', ']', 'P', 'Y', 'N', '|', 'q', 'i', 'J', '}', 'B',
       '&', 'W', '<', 'D', 'a', '<', 'W', ']', 'I', '(', '>', "'", 'l',
       '1', "'", 'o', 'G', 'M', '_', 'x', 't', '6', '9', '7', '<', 't',
       'o', 'i', ')'], dtype='<U1')

In [51]:
epochs = 30

In [52]:
model.fit(dataset, epochs=epochs)

Epoch 1/30
351/351 [==============================] - 47s 126ms/step - loss: 3.1805
Epoch 2/30
130/351 [==========>...................] - ETA: 29s - loss: 1.9527

KeyboardInterrupt: ignored

In [ ]:
from tensorflow.keras.models  import load_model

In [ ]:
model.save('NLP_shakespeare.h5')


In [ ]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)
model.load_weights('NLP_shakespeare.h5')

model.build(tf.TensorShape([1,None]))

In [ ]:
model.summary()

In [ ]:
def generate_text(model, start_seed, gen_size=500, temp=1.0):
  num_generate = gen_size
  input_eval = [char_to_ind[s] for s in start_seed]#vectorize le text du seed de depart 