In [20]:
import numpy as np

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[8]

8

In [24]:
arr[1:5]

array([1, 2, 3, 4])

In [25]:
arr[:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[:5]=100

In [28]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
arr = np.arange(0,11)

In [30]:
slice_of_arr = arr[0:5]

In [31]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [32]:
slice_of_arr[:]=99

In [33]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [34]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
arr_copy = arr.copy()

In [36]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d.shape

(3, 3)

In [40]:
arr_2d[2]

array([35, 40, 45])

In [41]:
arr_2d[1,1]

25

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr>4

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])