In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
nested_list=[[1,2],[3,4],[5,6]]

In [ ]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2) # rand entre 0 et 1

array([0.97076261, 0.93407596])

In [ ]:
np.random.rand(3,4)

array([[0.48901474, 0.56944349, 0.21702131, 0.63388073],
       [0.59202873, 0.35076959, 0.75666829, 0.95538943],
       [0.34849121, 0.22251555, 0.34997708, 0.720303  ]])

In [ ]:
np.random.randn(5,5) # randn entre -1 et 1 

array([[-0.0258788 ,  1.01826136,  0.76815898, -0.25405354,  0.16176452],
       [-0.64718772,  0.15640239,  1.72673755, -0.52246859, -0.63062393],
       [ 0.3798911 ,  1.49905406,  0.78400628,  0.72485303, -0.22705294],
       [ 1.085371  , -0.28311812,  0.67011301, -3.26531311, -0.92881417],
       [-1.41554135,  1.63188756, -2.98101053, -1.83369817, -0.53232084]])

In [ ]:
np.random.randint(1,100, (2,3))

array([[24, 30, 43],
       [30, 60, 70]])

In [ ]:
np.random.seed(42) # deux lignes dans la meme cellule, permet de recuperer ls nombres aleatoires 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
ranarr.max()

39

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

9

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
myarr = np.random.rand(4)
myarr

array([0.43194502, 0.29122914, 0.61185289, 0.13949386])

In [ ]:
myarr.dtype

dtype('float64')