# Exercices NumPy

Maintenant que vous avez appris les bases de NumPy, testez vos connaissances. Vous commencerez par quelques tâches simples, puis vous aurez des questions plus complexes.

<div class="alert alert-danger" style="margin : 10px"><strong>NOTE IMPORTANTE !</strong> Assurez-vous de ne pas exécuter les cellules directement au-dessus des résultats pour ne pas les effacer !</div>

#### 1. Importer NumPy

#### 2. Créer un tableau de 10 zéros


In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Créer un tableau contenant 10 uns

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Créer un tableau de 10 cinq

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Créer un tableau d'entiers de 10 à 50

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Créer un tableau de tous les entiers pairs de 10 à 50

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Créer une matrice 3x3 avec des valeurs allant de 0 à 8

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Créer une matrice identité 3x3

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Utiliser NumPy pour générer un nombre aléatoire entre 0 et 1
NOTE : La valeur de votre résultat doit être différente de celle indiquée ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([0.10775124])

#### 10. Utiliser NumPy pour générer un tableau de 25 nombres aléatoires échantillonnés à partir d'une distribution normale standard
NOTE : Les valeurs de votre résultat doivent être différentes de celles indiquées ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([ 0.98191795,  0.11015843,  1.14926955,  0.84784287,  0.7212745 ,
        0.26564431,  0.02445377, -0.85878697,  0.66952072, -0.48454133,
        0.07564346,  1.08963205, -0.10492075,  1.6678985 , -1.01509052,
        0.08806938, -0.11293401, -0.5444564 , -0.76051702, -1.04008647,
       -0.72605723,  0.23374034,  0.24055805, -0.86450581, -1.17211855])

#### 11. Créer la matrice suivante :

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Créer un tableau de 20 points espacés linéairement entre 0 et 1 :

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexation et sélection NumPy

Pour une matrice donnée de départ (n'oubliez pas de lancer la cellule ci-dessous !),vous aurez à reproduire les résultats de la matrice résultante :

In [ ]:
# EXECUTER CETTE CELLULE - C'EST NOTRE MATRICE DE DÉPART
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Écrivez un code qui reproduit la sortie indiquée ci-dessous.
Attention de ne pas exécuter la cellule immédiatement au-dessus de la sortie, sinon vous ne pourrez plus voir celle-ci.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Ecrivez un code qui reproduit le résultat indiqué ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

20

#### 15. Ecrivez un code qui reproduit le résultat indiqué ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[ 2],
       [ 7],
       [12]])

#### 16. Ecrivez un code qui reproduit le résultat indiqué ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([21, 22, 23, 24, 25])

#### 17. Ecrivez un code qui reproduit le résultat indiqué ci-dessous.

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Opérations NumPy

18. Obtenir la somme de toutes les valeurs de la matrice mat


In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

325

#### 19. Obtenir l'écart type des valeurs de la matrice mat

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

7.211102550927978

#### 20. Obtenir la somme de toutes les colonnes de la matrice mat

In [ ]:
# Code ici

In [ ]:
# Ne rien écrire ici

array([55, 60, 65, 70, 75])

## Question bonus
Nous avons beaucoup travaillé avec des données aléatoires avec NumPy, mais y a-t-il un moyen de s'assurer que nous obtenions toujours les mêmes nombres aléatoires ? Que signifie la valeur de seed ? Le nombre choisi est-il important ? [Cliquez ici pour un indice](https://www.google.com/search?q=numpy+random+seed)

Bon courage !